-- MySQL Script generated by MySQL Workbench
-- Sat Jan 23 15:23:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tubirra
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tubirra` ;

-- -----------------------------------------------------
-- Schema tubirra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tubirra` DEFAULT CHARACTER SET utf8mb4 ;
USE `tubirra` ;

-- -----------------------------------------------------
-- Table `tubirra`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`categorias` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(100) NULL DEFAULT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`datosuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`datosuser` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `altura` INT(11) NOT NULL,
  `codigo` INT(11) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` INT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UseDat_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_UseDat`
    FOREIGN KEY (`id_user`)
    REFERENCES `tubirra`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`formapago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`formapago` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`productos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `precio` FLOAT NOT NULL,
  `stock` INT(10) NOT NULL,
  `id_categoria` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CatPro_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_CatPro`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tubirra`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`imagenes` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `id_productos` INT(10) NOT NULL,
  `imagenes` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProIma_idx` (`id_productos` ASC) VISIBLE,
  CONSTRAINT `fk_ProIma`
    FOREIGN KEY (`id_productos`)
    REFERENCES `tubirra`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`pedido` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `id_producto` INT(10) NOT NULL,
  `id_user` INT(10) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `total` FLOAT NOT NULL,
  `id_formapago` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProPed_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_UsePed_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_ForPed_idx` (`id_formapago` ASC) VISIBLE,
  CONSTRAINT `fk_ForPed`
    FOREIGN KEY (`id_formapago`)
    REFERENCES `tubirra`.`formapago` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProPed`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tubirra`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UsePed`
    FOREIGN KEY (`id_user`)
    REFERENCES `tubirra`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
