-- MySQL Script generated by MySQL Workbench
-- Fri Jan 22 16:43:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tubirra
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tubirra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tubirra` DEFAULT CHARACTER SET utf8mb4 ;
USE `tubirra` ;

-- -----------------------------------------------------
-- Table `tubirra`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`categorias` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`datos_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`datos_user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL DEFAULT NULL,
  `altura` INT(10) NULL DEFAULT NULL,
  `codigo` INT(10) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` INT(15) NULL DEFAULT NULL,
  `id_user` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`formapago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`formapago` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `detalle` VARCHAR(500) NULL DEFAULT NULL,
  `stock` INT(10) NULL DEFAULT NULL,
  `categorias_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `tubirra`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`imagenes` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `productos_id` INT(11) NOT NULL,
  `imagenes` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productos_id_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `productos_id`
    FOREIGN KEY (`productos_id`)
    REFERENCES `tubirra`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`orden` (
  `id` INT(10) NOT NULL,
  `id_producto` VARCHAR(45) NULL,
  `id_formapago` INT(10) NOT NULL,
  `total` FLOAT NOT NULL,
  `cantidad` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orden_formapago1`
    FOREIGN KEY (`id_formapago`)
    REFERENCES `tubirra`.`formapago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tubirra`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tubirra`.`users` (
  `id` INT(10) NOT NULL,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  `apellido` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(100) NOT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
